name: Test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Run linter
        uses: ricardochaves/python-lint@v1.3.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-flake8-options: "--max-line-length=100"