name: Test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Run linter
        uses: TrueBrain/actions-flake8
        with:
          max_line_length: 100